
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



public class LogIn2 extends javax.swing.JFrame {
     


     
     Connection conn=null;
     PreparedStatement st=null;
     ResultSet rs=null;
    public LogIn2() throws SQLException {
        try {
            initComponents();
            LogIn login = new LogIn();
            login.setVisible(false);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LogIn2.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        upass = new javax.swing.JPasswordField();
        signin2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sign In Form");
        setForeground(java.awt.Color.darkGray);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setForeground(new java.awt.Color(51, 51, 55));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Close_Window_30px_1.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 30, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText(" Password  :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 150, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Username :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 150, 30));

        uname.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jPanel1.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 260, 30));

        upass.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel1.add(upass, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 260, 30));

        signin2.setBackground(new java.awt.Color(0, 153, 153));
        signin2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        signin2.setForeground(new java.awt.Color(255, 255, 255));
        signin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sign-in.png"))); // NOI18N
        signin2.setText("Sign In");
        signin2.setBorder(null);
        signin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signin2ActionPerformed(evt);
            }
        });
        jPanel1.add(signin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 110, 30));

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sign In");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 100, 30));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setForeground(new java.awt.Color(51, 51, 55));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 220));

        jLabel6.setBackground(new java.awt.Color(153, 153, 153));
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Accounts_main (Custom).png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 70, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(530, 211));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signin2ActionPerformed
       
        String username2=uname.getText();
         String pass2=new String(upass.getPassword());
       if (username2.equals("") || pass2.equals("")) {
           
        JOptionPane.showMessageDialog(null, "Enter valid username and password !");
           uname.setText("");
           upass.setText("");
          
       }
       
       else{
           String sql= "select * from signupdb where Username= ? and Password = ?";
           try{
               conn=DriverManager.getConnection("jdbc:mysql://localhost/SignUp_table","root","");
               st = conn.prepareStatement(sql);
               st.setString(1,uname.getText());
                st.setString(2,upass.getText()); 
                rs = st.executeQuery();
               if(rs.next()){
                  
                    this.dispose();
                     LogIn login = new LogIn();
                     login.setVisible(false);

                    NewForm newform=new NewForm();
                    newform.setVisible(true);
    
               }  else{
                    
                   JOptionPane.showMessageDialog(null, "Username or Password is incorrect !");
                    uname.setText("");
                    upass.setText("");
               }
               
           }  catch(HeadlessException | ClassNotFoundException | SQLException e){
               
               JOptionPane.showMessageDialog(null, e);
           }
       }
           
         
    }//GEN-LAST:event_signin2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton signin2;
    private javax.swing.JTextField uname;
    private javax.swing.JPasswordField upass;
    // End of variables declaration//GEN-END:variables

}
